version: '3.8'
services:
    node-api:
        container_name: eventbus_node_api
        restart: always
        image: library/node:14
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        ports:
            - "3000:3000"
        command: ${ENTRYPOINT_API}
        depends_on:
            - mysql
        networks:
            - eventbus

    event-consumer:
        container_name: eventbus_node_consumer
        restart: always
        image: library/node:14
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        command: ${ENTRYPOINT_CONSUMER}
        environment:
            - QUEUE_NAME=${EVENT_QUEUE_NAME}
        depends_on:
            - rabbitmq
        networks:
            - eventbus

    notification-consumer:
        container_name: eventbus_notification_consumer
        restart: always
        image: library/node:14
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        command: ${ENTRYPOINT_CONSUMER}
        environment:
            - QUEUE_NAME=${NOTIFICATION_QUEUE_NAME}
        depends_on:
            - rabbitmq
        networks:
            - eventbus

    mysql:
        container_name: eventbus_mysql
        image: library/mysql:8
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d/
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} status >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks:
            - eventbus

    rabbitmq:
        container_name: eventbus_rabbitmq
        image: library/rabbitmq:3.8.9
        restart: always
        hostname: eventbus-rmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics ping >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - eventbus

    apidoc:
        image: redocly/redoc
        restart: on-failure
        ports:
            - 3001:80
        volumes:
            - ./documentation/:/usr/share/nginx/html/documentation/
        environment:
            SPEC_URL: ./documentation/apidoc.yml
        networks:
            - eventbus

volumes:
    rabbitmq:
    db:

networks:
    eventbus:
        driver: bridge
