version: '3.8'
services:
    nodejs:
        restart: always
        build:
            context: ""
            dockerfile: .docker/nodejs/Dockerfile
            target: development
        volumes:
            - ./:/usr/src/app
        ports:
            - "3000:3000"
        command: npm run start:dev
