version: '3.8'
services:
    node:
        container_name: eventbus_node
        restart: on-failure
        image: library/node:14-alpine
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        ports:
            - "3000:3000"
        command: npm run start:dev
        networks:
            - eventbus

    mysql:
        container_name: eventbus_mysql
        image: library/mysql:8
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d/
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} status >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks:
            - eventbus

    rabbitmq:
        container_name: eventbus_rabbitmq
        image: library/rabbitmq:3
        restart: always
        hostname: eventbus-rmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics ping >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - eventbus

volumes:
    rabbitmq:
    db:

networks:
    eventbus:
        driver: bridge
