version: '3.8'
services:
    nodejs:
        restart: on-failure
        image: library/node:14-alpine
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        ports:
            - "3000:3000"
        command: npm run start:dev
