version: '3.8'
services:
    api:
        image: library/node:14
        container_name: eventbus_api
        restart: on-failure
        env_file:
            - .env
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        ports:
            - "3000:3000"
        command: npm run start:api:dev
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus

    event-consumer:
        image: library/node:14
        container_name: eventbus_event_consumer
        restart: on-failure
        env_file:
            - .env
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        command: npm run start:consumer:dev
        environment:
            - QUEUE_NAME=${EVENT_QUEUE_NAME}
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus

    notification-consumer:
        image: library/node:14
        container_name: eventbus_notification_consumer
        restart: on-failure
        env_file:
            - .env
        volumes:
            - ./:/app
        working_dir: /app
        user: node
        command: npm run start:consumer:dev
        environment:
            - QUEUE_NAME=${NOTIFICATION_QUEUE_NAME}
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus

    mysql:
        image: library/mysql:8
        container_name: eventbus_mysql
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d/
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} status >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks:
            - eventbus

    rabbitmq:
        image: library/rabbitmq:3.8-management
        container_name: eventbus_rabbitmq
        restart: on-failure
        hostname: eventbus-rmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics ping >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - eventbus

    apidoc:
        image: swaggerapi/swagger-ui
        container_name: eventbus_apidoc
        restart: on-failure
        ports:
            - "3001:8080"
        volumes:
            - ./documentation/:/usr/share/nginx/html/documentation/
        environment:
            URLS: "[ { url: './documentation/apidoc.yml', name: 'EventBus Service' } ]"
        networks:
            - eventbus

volumes:
    rabbitmq:
    db:

networks:
    eventbus:
        driver: bridge
