version: '3.8'
services:
    api:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_prod_api
        restart: always
        ports:
            - "3000:3000"
        command: npm run start:api:prod
        env_file:
            - .env
        environment:
            - MIGRATION_RUN=true
            - TZ=Europe/Kiev
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus_prod

    event-consumer:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_prod_event_consumer
        restart: always
        command: npm run start:consumer:prod
        env_file:
            - .env
        environment:
            - QUEUE_NAME=${EVENT_QUEUE_NAME}
            - TZ=Europe/Kiev
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus_prod

    notification-consumer:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_prod_notification_consumer
        restart: always
        command: npm run start:consumer:prod
        env_file:
            - .env
        environment:
            - QUEUE_NAME=${NOTIFICATION_QUEUE_NAME}
            - TZ=Europe/Kiev
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - eventbus_prod

    mysql:
        image: library/mysql:8
        container_name: eventbus_prod_mysql
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d/
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} status >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - TZ=Europe/Kiev
        networks:
            - eventbus_prod

    rabbitmq:
        image: library/rabbitmq:3.8
        container_name: eventbus_prod_rabbitmq
        restart: always
        hostname: eventbus-rmq
        environment:
            - TZ=Europe/Kiev
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics ping >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - eventbus_prod

volumes:
    rabbitmq:
    db:

networks:
    eventbus_prod:
        driver: bridge
