version: '3.8'
services:
    node-api:
        networks:
            eventbus:
                ipv4_address: 192.168.16.2
    event-consumer:
        networks:
            eventbus:
                ipv4_address: 192.168.16.3
    notification-consumer:
        networks:
            eventbus:
                ipv4_address: 192.168.16.4
    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD
        ports:
            - "3308:3306"
        networks:
            eventbus:
                ipv4_address: 192.168.16.6
    rabbitmq:
        image: library/rabbitmq:3.8.9-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            eventbus:
                ipv4_address: 192.168.16.5

    apidoc:
        networks:
            eventbus:
                ipv4_address: 192.168.16.7

networks:
    eventbus:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.16.0/24
