version: '3.8'
services:
    node-api:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_node_api
        restart: always
        env_file:
            - .env
        ports:
            - "3000:3000"
        command: npm run start:api:prod
        depends_on:
            - mysql
        networks:
            - eventbus

    event-consumer:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_node_consumer
        restart: always
        env_file:
            - .env
        command: npm run start:api:prod
        environment:
            - start:consumer:prod
        depends_on:
            - rabbitmq
        networks:
            - eventbus

    notification-consumer:
        image: ${DOCKER_REGISTRY}/eventbus-app-prod:${IMAGE_TAG}
        container_name: eventbus_notification_consumer
        restart: always
        env_file:
            - .env
        command: start:consumer:prod
        environment:
            - QUEUE_NAME=${NOTIFICATION_QUEUE_NAME}
        depends_on:
            - rabbitmq
        networks:
            - eventbus

    mysql:
        container_name: eventbus_mysql
        image: library/mysql:8
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d/
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} status >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        networks:
            - eventbus

    rabbitmq:
        container_name: eventbus_rabbitmq
        image: library/rabbitmq:3.8
        restart: always
        hostname: eventbus-rmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        healthcheck:
            test: rabbitmq-diagnostics ping >/dev/null 2>/dev/null
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - eventbus

volumes:
    rabbitmq:
    db:

networks:
    eventbus:
        driver: bridge
